// src/seo/keywords.ts
export const DEFAULT_KEYWORDS = [
  "trolley bag repair shop near me",
  "luggage repair Gaya",
  "luggage service near me",
  "suitcase repair near me",
  "trolley wheel repair",
  "trolly wheel repair near me",
  "trolly",
  "trolley",
  "bag repair shop Gaya",
  "bag repair shop near me",
  "trolley repair Gaya",
  "trolly repair Gaya",
  "trollery repair Gaya",
  "zip replacement Gaya",
  "bag handle repair Gaya",
  "jacket chain zip repair",
  "trolley bag shop near me",
  "leather jacket repairing shop near me",
  "jacket zipper repair near me",
  "vip bags repair shop near me",
  "tailor near me",
  "briefcase repair near me",
  "safari trolley bag chain repair",
  "suitcase lock repair near me",
  "trolley bag service centre near me",
  "trolley chain repair near me",
  "trolley bag lock repair near me",
];
